-- PASSO 1: Criar tabela
create table if not exists public.unidades (
  id            bigint generated always as identity primary key,
  sigla         text   not null,
  bloco         text,
  unidade       text   not null,
  fracao_ideal  text   not null default '',
  vagas         text   not null default '',
  unique (sigla, bloco, unidade)
);

create index if not exists unidades_sigla_unidade_idx on public.unidades (sigla, unidade);

-- PASSO 2: Importar dados
insert into public.unidades (sigla, bloco, unidade, fracao_ideal, vagas) values
  ('DMS', NULL, '101', 'fração ideal de terreno de 0,00349', 'sem vaga de garagem'),
  ('DMS', NULL, '102', 'fração ideal de terreno de 0,00347', 'sem vaga de garagem'),
  ('DMS', NULL, '301', 'fração ideal de terreno de 0,01275', 'com 1 (uma) vaga de garagem, de número 21, localizada no Térreo'),
  ('DMS', NULL, '401', 'fração ideal de terreno de 0,01275', 'com 1 (uma) vaga de garagem, de número 15, localizada no Térreo'),
  ('DMS', NULL, '501', 'fração ideal de terreno de 0,01275', 'com 1 (uma) vaga de garagem, de número 19, localizada no Térreo'),
  ('DMS', NULL, '601', 'fração ideal de terreno de 0,01275', 'com 1 (uma) vaga de garagem, de número 3, localizada no Térreo'),
  ('DMS', NULL, '701', 'fração ideal de terreno de 0,01333', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 7, localizada no Puc/ Garagem'),
  ('DMS', NULL, '801', 'fração ideal de terreno de 0,01333', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 9, localizada no Puc/ Garagem'),
  ('DMS', NULL, '901', 'fração ideal de terreno de 0,01347', 'com 1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 18, localizada no Semienterrado'),
  ('DMS', NULL, '1001', 'fração ideal de terreno de 0,01334', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 20, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1101', 'fração ideal de terreno de 0,01334', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 22, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1201', 'fração ideal de terreno de 0,01334', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 10, localizada no Semienterrado'),
  ('DMS', NULL, '1301', 'fração ideal de terreno de 0,01334', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 12, localizada no Semienterrado'),
  ('DMS', NULL, '1401', 'fração ideal de terreno de 0,01334', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 5, localizada no Térreo'),
  ('DMS', NULL, '302', 'fração ideal de terreno de 0,0124', 'com 1 (uma) vaga de garagem, de número 22, localizada no Térreo'),
  ('DMS', NULL, '402', 'fração ideal de terreno de 0,0124', 'com 1 (uma) vaga de garagem, de número 23, localizada no Semienterrado'),
  ('DMS', NULL, '502', 'fração ideal de terreno de 0,0124', 'com 1 (uma) vaga de garagem, de número 20, localizada no Térreo'),
  ('DMS', NULL, '602', 'fração ideal de terreno de 0,0124', 'com 1 (uma) vaga de garagem, de número 4, localizada no Térreo'),
  ('DMS', NULL, '702', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 6, localizada no Puc/ Garagem'),
  ('DMS', NULL, '802', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 8, localizada no Puc/ Garagem'),
  ('DMS', NULL, '902', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 10, localizada no Puc/ Garagem'),
  ('DMS', NULL, '1002', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 15, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1102', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 21, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1202', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 23, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1302', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 11, localizada no Semienterrado'),
  ('DMS', NULL, '1402', 'fração ideal de terreno de 0,01298', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 13, localizada no Semienterrado'),
  ('DMS', NULL, '303', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 4, localizada no Puc/ Garagem'),
  ('DMS', NULL, '403', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 13, localizada no Puc/ Garagem'),
  ('DMS', NULL, '503', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 17, localizada no Semienterrado'),
  ('DMS', NULL, '603', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 4, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '703', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 24, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '803', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 10, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '903', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 9, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1003', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 13, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1103', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 14, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1203', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 8, localizada no Térreo'),
  ('DMS', NULL, '1303', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 4, localizada no Semienterrado'),
  ('DMS', NULL, '1403', 'fração ideal de terreno de 0,00956', 'com 1 (uma) vaga de garagem, de número 22, localizada no Semienterrado'),
  ('DMS', NULL, '304', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 5, localizada no Puc/ Garagem'),
  ('DMS', NULL, '404', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 3, localizada no Puc/ Garagem'),
  ('DMS', NULL, '504', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 3, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '604', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 18, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '704', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 1, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '804', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 17, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '904', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 8, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1004', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 15, localizada no Semienterrado'),
  ('DMS', NULL, '1104', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 5, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1204', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 9, localizada no Semienterrado'),
  ('DMS', NULL, '1304', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 9, localizada no Térreo'),
  ('DMS', NULL, '1404', 'fração ideal de terreno de 0,00954', 'com 1 (uma) vaga de garagem, de número 19, localizada no Semienterrado'),
  ('DMS', NULL, '305', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 16, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '405', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 11, localizada no Puc/ Garagem'),
  ('DMS', NULL, '505', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 19, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '605', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 26, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '705', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 28, localizada no Semienterrado'),
  ('DMS', NULL, '805', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 27, localizada no Semienterrado'),
  ('DMS', NULL, '905', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 26, localizada no Semienterrado'),
  ('DMS', NULL, '1005', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 25, localizada no Semienterrado'),
  ('DMS', NULL, '1105', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 24, localizada no Semienterrado'),
  ('DMS', NULL, '1205', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 2, localizada no Semienterrado'),
  ('DMS', NULL, '1305', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 1, localizada no Semienterrado'),
  ('DMS', NULL, '1405', 'fração ideal de terreno de 0,01194', 'com 1 (uma) vaga de garagem, de número 23, localizada no Térreo'),
  ('DMS', NULL, '306', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 16, localizada no Térreo'),
  ('DMS', NULL, '406', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 16, localizada no Semienterrado'),
  ('DMS', NULL, '506', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 18, localizada no Térreo'),
  ('DMS', NULL, '606', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 12, localizada no Puc/ Garagem'),
  ('DMS', NULL, '706', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 2, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '806', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 12, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '906', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 7, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1006', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 6, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '1106', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 14, localizada no Semienterrado'),
  ('DMS', NULL, '1206', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 8, localizada no Semienterrado'),
  ('DMS', NULL, '1306', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 7, localizada no Semienterrado'),
  ('DMS', NULL, '1406', 'fração ideal de terreno de 0,01006', 'com 1 (uma) vaga de garagem, de número 20, localizada no Semienterrado'),
  ('DMS', NULL, '307', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 17, localizada no Térreo'),
  ('DMS', NULL, '407', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 2, localizada no Puc/ Garagem'),
  ('DMS', NULL, '507', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 14, localizada no Térreo'),
  ('DMS', NULL, '607', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 1, localizada no Puc/ Garagem'),
  ('DMS', NULL, '707', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 25, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '807', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 11, localizada no Pavimento Intermediário'),
  ('DMS', NULL, '907', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 7, localizada no Térreo'),
  ('DMS', NULL, '1007', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 6, localizada no Térreo'),
  ('DMS', NULL, '1107', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 5, localizada no Semienterrado'),
  ('DMS', NULL, '1207', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 6, localizada no Semienterrado'),
  ('DMS', NULL, '1307', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 3, localizada no Semienterrado'),
  ('DMS', NULL, '1407', 'fração ideal de terreno de 0,0099', 'com 1 (uma) vaga de garagem, de número 21, localizada no Semienterrado'),
  ('DMS', NULL, '1501', 'fração ideal de terreno de 0,01294', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 13, localizada no Térreo'),
  ('DMS', NULL, '1502', 'fração ideal de terreno de 0,01555', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 12, localizada no Térreo'),
  ('DMS', NULL, '1503', 'fração ideal de terreno de 0,01189', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 11, localizada no Térreo'),
  ('DMS', NULL, '1504', 'fração ideal de terreno de 0,01709', 'com 2 (duas) vagas de garagem, de número 1 e 2, todas localizadas no Térreo'),
  ('DMS', NULL, '1505', 'fração ideal de terreno de 0,0123', 'com 1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 10, localizada no Térreo'),
  ('AAZ', NULL, '101', 'fração ideal de terreno de 0,00196', 'SEM vaga de garagem'),
  ('AAZ', NULL, '102', 'fração ideal de terreno de 0,00202', 'SEM vaga de garagem'),
  ('AAZ', NULL, '201', 'fração ideal de terreno de 0,00766', '1 (uma) vaga de garagem, de número 1, localizada no semienterrado'),
  ('AAZ', NULL, '202', 'fração ideal de terreno de 0,0049', '1 (uma) vaga de garagem, de número 15, localizada no pavimento intermediário'),
  ('AAZ', NULL, '203', 'fração ideal de terreno de 0,00486', '1 (uma) vaga de garagem, de número 13, localizada no pavimento intermediário'),
  ('AAZ', NULL, '204', 'fração ideal de terreno de 0,00844', '2 (duas) vagas de garagem, de número 32 e 32A, todas localizadas no semienterrado'),
  ('AAZ', NULL, '205', 'fração ideal de terreno de 0,00856', '2 (duas) vagas de garagem, de número 31 e 31A, todas localizadas no semienterrado'),
  ('AAZ', NULL, '206', 'fração ideal de terreno de 0,0048', '1 (uma) vaga de garagem, de número 16, localizada no pavimento intermediário'),
  ('AAZ', NULL, '207', 'fração ideal de terreno de 0,00482', '1 (uma) vaga de garagem, de número 17, localizada no pavimento intermediário'),
  ('AAZ', NULL, '208', 'fração ideal de terreno de 0,00751', '1 (uma) vaga de garagem, de número 2, localizada no semienterrado'),
  ('AAZ', NULL, '301', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 6, localizada no semienterrado'),
  ('AAZ', NULL, '302', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 20, localizada no pavimento intermediário'),
  ('AAZ', NULL, '303', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 3, localizada no semienterrado'),
  ('AAZ', NULL, '304', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 30 e 30A, todas localizadas no semienterrado'),
  ('AAZ', NULL, '305', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 35 e 35A, todas localizadas no subsolo'),
  ('AAZ', NULL, '306', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 18, localizada no pavimento intermediário'),
  ('AAZ', NULL, '307', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 19, localizada no pavimento intermediário'),
  ('AAZ', NULL, '308', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 13, localizada no subsolo'),
  ('AAZ', NULL, '309', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '310', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '311', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '312', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 29, localizada no pavimento intermediário'),
  ('AAZ', NULL, '313', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 29, localizada no semienterrado'),
  ('AAZ', NULL, '314', 'fração ideal de terreno de 0,00242', 'SEM vaga de garagem'),
  ('AAZ', NULL, '315', 'fração ideal de terreno de 0,00242', 'SEM vaga de garagem'),
  ('AAZ', NULL, '316', 'fração ideal de terreno de 0,00256', 'SEM vaga de garagem'),
  ('AAZ', NULL, '401', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 5, localizada no semienterrado'),
  ('AAZ', NULL, '402', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 14, localizada no semienterrado'),
  ('AAZ', NULL, '403', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 15, localizada no semienterrado'),
  ('AAZ', NULL, '404', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 36 e 36A, todas localizadas no subsolo'),
  ('AAZ', NULL, '405', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 36 e 36A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '406', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 12, localizada no semienterrado'),
  ('AAZ', NULL, '407', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 13, localizada no semienterrado'),
  ('AAZ', NULL, '408', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 31, localizada no térreo'),
  ('AAZ', NULL, '409', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '410', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '411', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '412', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 34, localizada no semienterrado'),
  ('AAZ', NULL, '413', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 35, localizada no pavimento intermediário'),
  ('AAZ', NULL, '414', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '415', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '416', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '501', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 4, localizada no semienterrado'),
  ('AAZ', NULL, '502', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 16, localizada no subsolo'),
  ('AAZ', NULL, '503', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 17, localizada no subsolo'),
  ('AAZ', NULL, '504', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 37 e 37A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '505', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 38 e 38A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '506', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 14, localizada no subsolo'),
  ('AAZ', NULL, '507', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 15, localizada no subsolo'),
  ('AAZ', NULL, '508', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 32, localizada no térreo'),
  ('AAZ', NULL, '509', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '510', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '511', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '512', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 33, localizada no subsolo'),
  ('AAZ', NULL, '513', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 31, localizada no pavimento intermediário'),
  ('AAZ', NULL, '514', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '515', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '516', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '601', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 11, localizada no semienterrado'),
  ('AAZ', NULL, '602', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 23, localizada no pavimento intermediário'),
  ('AAZ', NULL, '603', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 24, localizada no pavimento intermediário'),
  ('AAZ', NULL, '604', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 10 e 10A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '605', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 9 e 9A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '606', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 21, localizada no pavimento intermediário'),
  ('AAZ', NULL, '607', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 22, localizada no pavimento intermediário'),
  ('AAZ', NULL, '608', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 33, localizada no térreo'),
  ('AAZ', NULL, '609', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '610', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '611', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no pavimento intermediário'),
  ('AAZ', NULL, '612', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 27, localizada no subsolo'),
  ('AAZ', NULL, '613', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 23, localizada no semienterrado'),
  ('AAZ', NULL, '614', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '615', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '616', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '701', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 10, localizada no semienterrado'),
  ('AAZ', NULL, '702', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 27, localizada no pavimento intermediário'),
  ('AAZ', NULL, '703', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 28, localizada no pavimento intermediário'),
  ('AAZ', NULL, '704', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 11 e 11A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '705', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 9 e 9A, todas localizadas no subsolo'),
  ('AAZ', NULL, '706', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 25, localizada no pavimento intermediário'),
  ('AAZ', NULL, '707', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 26, localizada no pavimento intermediário'),
  ('AAZ', NULL, '708', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 34, localizada no térreo'),
  ('AAZ', NULL, '709', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '710', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '711', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '712', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 32, localizada no subsolo'),
  ('AAZ', NULL, '713', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 31, localizada no subsolo'),
  ('AAZ', NULL, '714', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '715', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '716', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '801', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 9, localizada no semienterrado'),
  ('AAZ', NULL, '802', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 20, localizada no subsolo'),
  ('AAZ', NULL, '803', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 21, localizada no subsolo'),
  ('AAZ', NULL, '804', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 11 e 11A, todas localizadas no subsolo'),
  ('AAZ', NULL, '805', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 10 e 10A, todas localizadas no subsolo'),
  ('AAZ', NULL, '806', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 18, localizada no subsolo'),
  ('AAZ', NULL, '807', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 19, localizada no subsolo'),
  ('AAZ', NULL, '808', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 35, localizada no térreo'),
  ('AAZ', NULL, '809', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '810', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '811', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '812', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 30, localizada no subsolo'),
  ('AAZ', NULL, '813', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 29, localizada no subsolo'),
  ('AAZ', NULL, '814', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '815', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '816', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '901', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 8, localizada no semienterrado'),
  ('AAZ', NULL, '902', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 18, localizada no semienterrado'),
  ('AAZ', NULL, '903', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 19, localizada no semienterrado'),
  ('AAZ', NULL, '904', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 7 e 7A, todas localizadas no subsolo'),
  ('AAZ', NULL, '905', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 8 e 8A, todas localizadas no subsolo'),
  ('AAZ', NULL, '906', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 16, localizada no semienterrado'),
  ('AAZ', NULL, '907', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 17, localizada no semienterrado'),
  ('AAZ', NULL, '908', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 9, localizada no térreo'),
  ('AAZ', NULL, '909', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '910', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '911', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '912', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 25, localizada no subsolo'),
  ('AAZ', NULL, '913', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 37, localizada no subsolo'),
  ('AAZ', NULL, '914', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '915', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '916', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1001', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 7, localizada no semienterrado'),
  ('AAZ', NULL, '1002', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 23, localizada no subsolo'),
  ('AAZ', NULL, '1003', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 38, localizada no subsolo'),
  ('AAZ', NULL, '1004', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 5 e 5A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1005', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 6 e 6A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1006', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 20, localizada no semienterrado'),
  ('AAZ', NULL, '1007', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 24, localizada no subsolo'),
  ('AAZ', NULL, '1008', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 8, localizada no térreo'),
  ('AAZ', NULL, '1009', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1010', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1011', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1012', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 33, localizada no semienterrado'),
  ('AAZ', NULL, '1013', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 28, localizada no semienterrado'),
  ('AAZ', NULL, '1014', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1015', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1016', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1101', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 3, localizada no térreo'),
  ('AAZ', NULL, '1102', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 24, localizada no térreo'),
  ('AAZ', NULL, '1103', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 25, localizada no térreo'),
  ('AAZ', NULL, '1104', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 3 e 3A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1105', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 4 e 4A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1106', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 22, localizada no subsolo'),
  ('AAZ', NULL, '1107', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 23, localizada no térreo'),
  ('AAZ', NULL, '1108', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 7, localizada no térreo'),
  ('AAZ', NULL, '1109', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1110', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1111', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1112', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 27, localizada no semienterrado'),
  ('AAZ', NULL, '1113', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 26, localizada no semienterrado'),
  ('AAZ', NULL, '1114', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1115', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1116', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1201', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 2, localizada no térreo'),
  ('AAZ', NULL, '1202', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 27, localizada no térreo'),
  ('AAZ', NULL, '1203', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 28, localizada no térreo'),
  ('AAZ', NULL, '1204', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 12 e 12A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1205', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 2 e 2A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1206', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 26, localizada no térreo'),
  ('AAZ', NULL, '1207', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 14, localizada no térreo'),
  ('AAZ', NULL, '1208', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 6, localizada no térreo'),
  ('AAZ', NULL, '1209', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1210', 'fração ideal de terreno de 0,00271', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1211', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1212', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 25, localizada no semienterrado'),
  ('AAZ', NULL, '1213', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 21, localizada no semienterrado'),
  ('AAZ', NULL, '1214', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1215', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1216', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1301', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 1, localizada no térreo'),
  ('AAZ', NULL, '1302', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 13, localizada no térreo'),
  ('AAZ', NULL, '1303', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 12, localizada no térreo'),
  ('AAZ', NULL, '1304', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 8 e 8A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1305', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 1 e 1A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1306', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 29, localizada no térreo'),
  ('AAZ', NULL, '1307', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 30, localizada no térreo'),
  ('AAZ', NULL, '1308', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 5, localizada no térreo'),
  ('AAZ', NULL, '1309', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, de número 28, localizada no subsolo'),
  ('AAZ', NULL, '1310', 'fração ideal de terreno de 0,00281', '1 (uma) vaga de garagem, de número 26, localizada no subsolo'),
  ('AAZ', NULL, '1311', 'fração ideal de terreno de 0,00304', '1 (uma) vaga de garagem, de número 33, localizada no pavimento intermediário'),
  ('AAZ', NULL, '1312', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 19, localizada no térreo'),
  ('AAZ', NULL, '1313', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 20, localizada no térreo'),
  ('AAZ', NULL, '1314', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1315', 'fração ideal de terreno de 0,00268', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1316', 'fração ideal de terreno de 0,00283', '1 (uma) vaga de garagem, do tipo PALLET, localizada no subsolo ou semienterrado'),
  ('AAZ', NULL, '1401', 'fração ideal de terreno de 0,00644', '1 (uma) vaga de garagem, de número 4, localizada no térreo'),
  ('AAZ', NULL, '1402', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 14, localizada no pavimento intermediário'),
  ('AAZ', NULL, '1403', 'fração ideal de terreno de 0,00408', '1 (uma) vaga de garagem, de número 12, localizada no subsolo'),
  ('AAZ', NULL, '1404', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 1 e 1A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1405', 'fração ideal de terreno de 0,00758', '2 (duas) vagas de garagem, de número 2 e 2A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1406', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 11, localizada no térreo'),
  ('AAZ', NULL, '1407', 'fração ideal de terreno de 0,00405', '1 (uma) vaga de garagem, de número 10, localizada no térreo'),
  ('AAZ', NULL, '1408', 'fração ideal de terreno de 0,00681', '2 (duas) vagas de garagem, de número 34 e 34A, todas localizadas no subsolo'),
  ('AAZ', NULL, '1409', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, de número 24, localizada no semienterrado'),
  ('AAZ', NULL, '1410', 'fração ideal de terreno de 0,00281', '1 (uma) vaga de garagem, de número 22, localizada no semienterrado'),
  ('AAZ', NULL, '1411', 'fração ideal de terreno de 0,00304', '1 (uma) vaga de garagem, de número 18, localizada no térreo'),
  ('AAZ', NULL, '1412', 'fração ideal de terreno de 0,00619', '1 (uma) vaga de garagem, de número 21, localizada no térreo'),
  ('AAZ', NULL, '1413', 'fração ideal de terreno de 0,00598', '1 (uma) vaga de garagem, de número 22, localizada no térreo'),
  ('AAZ', NULL, '1414', 'fração ideal de terreno de 0,00279', '1 (uma) vaga de garagem, de número 34, localizada no pavimento intermediário'),
  ('AAZ', NULL, '1415', 'fração ideal de terreno de 0,00279', '1 (uma) vaga de garagem, de número 32, localizada no pavimento intermediário'),
  ('AAZ', NULL, '1416', 'fração ideal de terreno de 0,00294', '1 (uma) vaga de garagem, de número 30, localizada no pavimento intermediário'),
  ('AAZ', NULL, '1501', 'fração ideal de terreno de 0,00745', '2 (duas) vagas de garagem, de número 3 e 3A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1502', 'fração ideal de terreno de 0,00947', '2 (duas) vagas de garagem, de número 7 e 7A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1503', 'fração ideal de terreno de 0,00947', '2 (duas) vagas de garagem, de número 6 e 6A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1504', 'fração ideal de terreno de 0,00739', '2 (duas) vagas de garagem, de número 5 e 5A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1505', 'fração ideal de terreno de 0,00619', '2 (duas) vagas de garagem, de número 4 e 4A, todas localizadas no pavimento intermediário'),
  ('AAZ', NULL, '1506', 'fração ideal de terreno de 0,00807', '2 (duas) vagas de garagem, de número 17 e 17A, todas localizadas no térreo'),
  ('AAZ', NULL, '1507', 'fração ideal de terreno de 0,00939', '2 (duas) vagas de garagem, de número 15 e 15A, todas localizadas no térreo'),
  ('AAZ', NULL, '1508', 'fração ideal de terreno de 0,00883', '2 (duas) vagas de garagem, de número 16 e 16A, todas localizadas no térreo'),
  ('BAK', NULL, '101', 'fração ideal de terreno de 0,00274', 'sem vaga de garagem'),
  ('BAK', NULL, '102', 'fração ideal de terreno de 0,00414', 'sem vaga de garagem'),
  ('BAK', NULL, '103', 'fração ideal de terreno de 0,0042', 'sem vaga de garagem'),
  ('BAK', NULL, '104', 'fração ideal de terreno de 0,00417', 'sem vaga de garagem'),
  ('BAK', NULL, '105', 'fração ideal de terreno de 0,00417', 'sem vaga de garagem'),
  ('BAK', NULL, '106', 'fração ideal de terreno de 0,00418', 'sem vaga de garagem'),
  ('BAK', NULL, '107', 'fração ideal de terreno de 0,00418', 'sem vaga de garagem'),
  ('BAK', NULL, '401', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 12 e 12A, todas localizadas no Subsolo'),
  ('BAK', NULL, '402', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 13 e 13A, todas localizadas no Subsolo'),
  ('BAK', NULL, '403', 'fração ideal de terreno de 0,01796', '1 (uma) vaga de garagem, de número 42, localizada no PUC'),
  ('BAK', NULL, '404', 'fração ideal de terreno de 0,01799', '1 (uma) vaga de garagem, de número 44, localizada no PUC'),
  ('BAK', NULL, '501', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 10 e 10A, todas localizadas no Subsolo'),
  ('BAK', NULL, '502', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 11 e 11A, todas localizadas no Subsolo'),
  ('BAK', NULL, '503', 'fração ideal de terreno de 0,01796', '1 (uma) vaga de garagem, de número 16, localizada no Semienterrado'),
  ('BAK', NULL, '504', 'fração ideal de terreno de 0,01799', '1 (uma) vaga de garagem, de número 15, localizada no Semienterrado'),
  ('BAK', NULL, '601', 'fração ideal de terreno de 0,01967', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 07, localizada no Subsolo'),
  ('BAK', NULL, '602', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 08 e 08A, todas localizadas no Subsolo'),
  ('BAK', NULL, '603', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 14 e 14A, todas localizadas no Subsolo'),
  ('BAK', NULL, '604', 'fração ideal de terreno de 0,01799', '1 (uma) vaga de garagem, de número 18, localizada no Semienterrado'),
  ('BAK', NULL, '701', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 46 e 46A, todas localizadas no PUC'),
  ('BAK', NULL, '702', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 47 e 47A, todas localizadas no PUC'),
  ('BAK', NULL, '703', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 06 e 06A, todas localizadas no Subsolo'),
  ('BAK', NULL, '704', 'fração ideal de terreno de 0,01887', '2 (duas) vagas de garagem, de número 09 e 09A, todas localizadas no Subsolo'),
  ('BAK', NULL, '801', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 43 e 43A, todas localizadas no PUC'),
  ('BAK', NULL, '802', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 45 e 45A, todas localizadas no PUC'),
  ('BAK', NULL, '803', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 04 e 04A, todas localizadas no Subsolo'),
  ('BAK', NULL, '804', 'fração ideal de terreno de 0,01887', '2 (duas) vagas de garagem, de número 05 e 05A, todas localizadas no Subsolo'),
  ('BAK', NULL, '901', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 40 e 40A, todas localizadas no PUC'),
  ('BAK', NULL, '902', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 41 e 41A, todas localizadas no PUC'),
  ('BAK', NULL, '903', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 02 e 02A, todas localizadas no Subsolo'),
  ('BAK', NULL, '904', 'fração ideal de terreno de 0,01887', '2 (duas) vagas de garagem, de número 03 e 03A, todas localizadas no Subsolo'),
  ('BAK', NULL, '1001', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 35 e 35A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1002', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 34 e 34A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1003', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 01 e 01A, todas localizadas no Subsolo'),
  ('BAK', NULL, '1004', 'fração ideal de terreno de 0,01869', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 50, localizada no PUC'),
  ('BAK', NULL, '1101', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 32 e 32A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1102', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 33 e 33A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1103', 'fração ideal de terreno de 0,01884', '2 (duas) vagas de garagem, de número 48 e 48A, todas localizadas no PUC'),
  ('BAK', NULL, '1104', 'fração ideal de terreno de 0,01869', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 49, localizada no PUC'),
  ('BAK', NULL, '1201', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 30 e 30A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1202', 'fração ideal de terreno de 0,01985', '2 (duas) vagas de garagem, de número 31 e 31A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1203', 'fração ideal de terreno de 0,01866', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 38, localizada no PUC'),
  ('BAK', NULL, '1204', 'fração ideal de terreno de 0,01869', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 39, localizada no PUC'),
  ('BAK', NULL, '1301', 'fração ideal de terreno de 0,01967', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 29, localizada no Garagem Adicional'),
  ('BAK', NULL, '1302', 'fração ideal de terreno de 0,01967', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 28, localizada no Garagem Adicional'),
  ('BAK', NULL, '1303', 'fração ideal de terreno de 0,01866', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 36, localizada no PUC'),
  ('BAK', NULL, '1304', 'fração ideal de terreno de 0,01869', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 37, localizada no PUC'),
  ('BAK', NULL, '1401', 'fração ideal de terreno de 0,02094', '2 (duas) vagas de garagem, de número 27 e 27A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1402', 'fração ideal de terreno de 0,02094', '2 (duas) vagas de garagem, de número 26 e 26A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1403', 'fração ideal de terreno de 0,02019', '1 (uma) vaga de garagem estendida com 9,00x2,50m, de número 21, localizada no Térreo'),
  ('BAK', NULL, '1404', 'fração ideal de terreno de 0,02039', '2 (duas) vagas de garagem, de número 17 e 17A, todas localizadas no Semienterrado'),
  ('BAK', NULL, '1501', 'fração ideal de terreno de 0,02704', '2 (duas) vagas de garagem, de número 22 e 22A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1502', 'fração ideal de terreno de 0,02716', '2 (duas) vagas de garagem, de número 23 e 23A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1503', 'fração ideal de terreno de 0,02036', '2 (duas) vagas de garagem, de número 24 e 24A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1504', 'fração ideal de terreno de 0,02039', '2 (duas) vagas de garagem, de número 25 e 25A, todas localizadas no Garagem Adicional'),
  ('BAK', NULL, '1601', 'fração ideal de terreno de 0,02673', '2 (duas) vagas de garagem, de número 19 e 20, todas localizadas no Térreo'),
  ('BCO', NULL, '101', 'fração ideal de terreno de 0,00502', 'SEM vaga de garagem'),
  ('BCO', NULL, '102', 'fração ideal de terreno de 0,03054', 'com direito a 8 (oito) vagas de garagem, de números 1, 2, 3, 4, 5, 5A, 6 E 6A , todas localizadas no JIRAU  '),
  ('BCO', NULL, '202', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '203', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '204', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '205', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '206', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '207', 'fração ideal de terreno de 0,00457', 'SEM vaga de garagem'),
  ('BCO', NULL, '208', 'fração ideal de terreno de 0,00399', 'SEM vaga de garagem'),
  ('BCO', NULL, '209', 'fração ideal de terreno de 0,00439', 'SEM vaga de garagem'),
  ('BCO', NULL, '210', 'fração ideal de terreno de 0,00415', 'SEM vaga de garagem'),
  ('BCO', NULL, '211', 'fração ideal de terreno de 0,00415', 'SEM vaga de garagem'),
  ('BCO', NULL, '212', 'fração ideal de terreno de 0,00415', 'SEM vaga de garagem'),
  ('BCO', NULL, '213', 'fração ideal de terreno de 0,00415', 'SEM vaga de garagem'),
  ('BCO', NULL, '214', 'fração ideal de terreno de 0,00415', 'SEM vaga de garagem'),
  ('BCO', NULL, '301', 'fração ideal de terreno de 0,00427', 'SEM vaga de garagem'),
  ('BCO', NULL, '302', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '303', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '304', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '305', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '306', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '307', 'fração ideal de terreno de 0,00457', 'SEM vaga de garagem'),
  ('BCO', NULL, '308', 'fração ideal de terreno de 0,00399', 'SEM vaga de garagem'),
  ('BCO', NULL, '309', 'fração ideal de terreno de 0,00439', 'SEM vaga de garagem'),
  ('BCO', NULL, '310', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '311', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '312', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '313', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '314', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '315', 'fração ideal de terreno de 0,00411', 'SEM vaga de garagem'),
  ('BCO', NULL, '316', 'fração ideal de terreno de 0,00387', 'SEM vaga de garagem'),
  ('BCO', NULL, '401', 'fração ideal de terreno de 0,00427', 'SEM vaga de garagem'),
  ('BCO', NULL, '402', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '403', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '404', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '405', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '406', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '407', 'fração ideal de terreno de 0,00457', 'SEM vaga de garagem'),
  ('BCO', NULL, '408', 'fração ideal de terreno de 0,00399', 'SEM vaga de garagem'),
  ('BCO', NULL, '409', 'fração ideal de terreno de 0,00439', 'SEM vaga de garagem'),
  ('BCO', NULL, '410', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '411', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '412', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '413', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '414', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '415', 'fração ideal de terreno de 0,00411', 'SEM vaga de garagem'),
  ('BCO', NULL, '416', 'fração ideal de terreno de 0,00387', 'SEM vaga de garagem'),
  ('BCO', NULL, '501', 'fração ideal de terreno de 0,00427', 'SEM vaga de garagem'),
  ('BCO', NULL, '502', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '503', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '504', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '505', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '506', 'fração ideal de terreno de 0,0035', 'SEM vaga de garagem'),
  ('BCO', NULL, '507', 'fração ideal de terreno de 0,00457', 'SEM vaga de garagem'),
  ('BCO', NULL, '508', 'fração ideal de terreno de 0,00399', 'SEM vaga de garagem'),
  ('BCO', NULL, '509', 'fração ideal de terreno de 0,00439', 'SEM vaga de garagem'),
  ('BCO', NULL, '510', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '511', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '512', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '513', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '514', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '515', 'fração ideal de terreno de 0,00411', 'SEM vaga de garagem'),
  ('BCO', NULL, '516', 'fração ideal de terreno de 0,00387', 'SEM vaga de garagem'),
  ('BCO', NULL, '610', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '611', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '612', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '613', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '614', 'fração ideal de terreno de 0,00332', 'SEM vaga de garagem'),
  ('BCO', NULL, '615', 'fração ideal de terreno de 0,00411', 'SEM vaga de garagem'),
  ('BCO', NULL, '701', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 7 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '702', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '703', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '704', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '705', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 17 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '706', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 16 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '707', 'fração ideal de terreno de 0,00459', 'SEM vaga de garagem'),
  ('BCO', NULL, '708', 'fração ideal de terreno de 0,00459', 'SEM vaga de garagem'),
  ('BCO', NULL, '709', 'fração ideal de terreno de 0,00459', 'SEM vaga de garagem'),
  ('BCO', NULL, '710', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 15 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '801', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 14 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '802', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '803', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '804', 'fração ideal de terreno de 0,00481', 'SEM vaga de garagem'),
  ('BCO', NULL, '805', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 13 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '806', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 12 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '807', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '808', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '809', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '810', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 11 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '901', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 10 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '902', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '903', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '904', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '905', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 9 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '906', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 8 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '907', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '908', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '909', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '910', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 5 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '1001', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 4 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '1002', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '1003', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '1004', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '1005', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 3 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '1006', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 16 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1007', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Garagem Adicional  '),
  ('BCO', NULL, '1008', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1009', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1010', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 15 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1101', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 14 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1102', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1103', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1104', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1105', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 13 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1106', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 12 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1107', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1108', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1109', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1110', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 11 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1201', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 10 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1202', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1203', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1204', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1205', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 9 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1206', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 8 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1207', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1208', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1209', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1210', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 7 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1301', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 6 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1302', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1303', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1304', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1305', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 5 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1306', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 4 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1307', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1308', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1309', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1310', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 3 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1401', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 2 , localizada no Subsolo 2  '),
  ('BCO', NULL, '1402', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1403', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1404', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1405', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 10 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1406', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 9 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1407', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1408', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1409', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1410', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 8 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1501', 'fração ideal de terreno de 0,00866', 'com direito a 1 (uma) vaga de garagem, de número 7 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1502', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1503', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1504', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1505', 'fração ideal de terreno de 0,00906', 'com direito a 1 (uma) vaga de garagem, de número 6 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1506', 'fração ideal de terreno de 0,0088', 'com direito a 1 (uma) vaga de garagem, de número 5 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1507', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1508', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1509', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1510', 'fração ideal de terreno de 0,00842', 'com direito a 1 (uma) vaga de garagem, de número 4 , localizada no Subsolo 1  '),
  ('BCO', NULL, '1601', 'fração ideal de terreno de 0,01546', 'com direito a 2 (duas) vagas de garagem, de números 1 E 1A , todas localizadas no Garagem Adicional  '),
  ('BCO', NULL, '1602', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1603', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1604', 'fração ideal de terreno de 0,00526', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1605', 'fração ideal de terreno de 0,01645', 'com direito a 2 (duas) vagas de garagem, de números 2 e 2A , todas localizadas no Garagem Adicional  '),
  ('BCO', NULL, '1606', 'fração ideal de terreno de 0,01599', 'com direito a 2 (duas) vagas de garagem, de números 1 e 1A , todas localizadas no Subsolo 1  '),
  ('BCO', NULL, '1607', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1608', 'fração ideal de terreno de 0,00504', 'com direito a 1 (uma) vaga de garagem, do tipo PALLET, localizada no Subsolo 1 ou Subsolo 2  '),
  ('BCO', NULL, '1609', 'fração ideal de terreno de 0,00521', 'com direito a 1 (uma) vaga de garagem, de número 6 , localizada no Garagem Adicional  '),
  ('BCO', NULL, '1610', 'fração ideal de terreno de 0,01506', 'com direito a 2 (duas) vagas de garagem, de números 2 e 2A , todas localizadas no Subsolo 1  '),
  ('BCO', NULL, '1701', 'fração ideal de terreno de 0,01645', 'com direito a 2 (duas) vagas de garagem, de números 1 e 1A , todas localizadas no Subsolo 2  '),
  ('BCO', NULL, '1702', 'fração ideal de terreno de 0,01564', 'com direito a 2 (duas) vagas de garagem, de números 3 e 3A , todas localizadas no Subsolo 1  '),
  ('H23', NULL, '201', 'fração ideal de terreno de 0,0174', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 17, localizada no Subsolo'),
  ('H23', NULL, '202', 'fração ideal de terreno de 0,02314', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 14, localizada no Semienterrado'),
  ('H23', NULL, '301', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 18, localizada no Subsolo'),
  ('H23', NULL, '302', 'fração ideal de terreno de 0,02241', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 5, localizada no Pavimento Intermediário'),
  ('H23', NULL, '303', 'fração ideal de terreno de 0,02165', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 6, localizada no Pavimento Intermediário'),
  ('H23', NULL, '304', 'fração ideal de terreno de 0,0141', '1 (uma) vaga de garagem, de número 6, localizada no Subsolo'),
  ('H23', NULL, '401', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 15, localizada no Semienterrado'),
  ('H23', NULL, '402', 'fração ideal de terreno de 0,02241', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 3, localizada no Pavimento Intermediário'),
  ('H23', NULL, '403', 'fração ideal de terreno de 0,02165', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 4, localizada no Pavimento Intermediário'),
  ('H23', NULL, '404', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 7, localizada no Pavimento Intermediário'),
  ('H23', NULL, '501', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 21, localizada no Subsolo'),
  ('H23', NULL, '502', 'fração ideal de terreno de 0,02241', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 10, localizada no Pavimento Intermediário'),
  ('H23', NULL, '503', 'fração ideal de terreno de 0,02165', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 9, localizada no Pavimento Intermediário'),
  ('H23', NULL, '504', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 8, localizada no Pavimento Intermediário'),
  ('H23', NULL, '601', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 7, localizada no Semienterrado'),
  ('H23', NULL, '602', 'fração ideal de terreno de 0,02241', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 1, localizada no Pavimento Intermediário'),
  ('H23', NULL, '603', 'fração ideal de terreno de 0,02165', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 2, localizada no Pavimento Intermediário'),
  ('H23', NULL, '604', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 8, localizada no Semienterrado'),
  ('H23', NULL, '701', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 2, localizada no Semienterrado'),
  ('H23', NULL, '702', 'fração ideal de terreno de 0,02241', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 16, localizada no Semienterrado'),
  ('H23', NULL, '703', 'fração ideal de terreno de 0,02165', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 5, localizada no Semienterrado'),
  ('H23', NULL, '704', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 1, localizada no Semienterrado'),
  ('H23', NULL, '801', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 3, localizada no Semienterrado'),
  ('H23', NULL, '802', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 7 e 8, todas localizadas no Subsolo'),
  ('H23', NULL, '803', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 9 e 10, todas localizadas no Subsolo'),
  ('H23', NULL, '804', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 1, localizada no Subsolo'),
  ('H23', NULL, '901', 'fração ideal de terreno de 0,01533', '2 (duas) vagas de garagem, de número 1 e 1A, todas localizadas no Térreo'),
  ('H23', NULL, '902', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 11 e 20, todas localizadas no Subsolo'),
  ('H23', NULL, '903', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 12 e 13, todas localizadas no Subsolo'),
  ('H23', NULL, '904', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 2, localizada no Subsolo'),
  ('H23', NULL, '1001', 'fração ideal de terreno de 0,01533', '2 (duas) vagas de garagem, de número 5 e 5A, todas localizadas no Térreo'),
  ('H23', NULL, '1002', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 2 e 2A, todas localizadas no Térreo'),
  ('H23', NULL, '1003', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 3 e 3A, todas localizadas no Térreo'),
  ('H23', NULL, '1004', 'fração ideal de terreno de 0,01483', '2 (duas) vagas de garagem, de número 4 e 4A, todas localizadas no Térreo'),
  ('H23', NULL, '1101', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 4, localizada no Semienterrado'),
  ('H23', NULL, '1102', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 14 e 15, todas localizadas no Subsolo'),
  ('H23', NULL, '1103', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 16 e 19, todas localizadas no Subsolo'),
  ('H23', NULL, '1104', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 3, localizada no Subsolo'),
  ('H23', NULL, '1201', 'fração ideal de terreno de 0,01533', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 6, localizada no Semienterrado'),
  ('H23', NULL, '1202', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 17 e 18, todas localizadas no Semienterrado'),
  ('H23', NULL, '1203', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 22 e 23, todas localizadas no Subsolo'),
  ('H23', NULL, '1204', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 4, localizada no Subsolo'),
  ('H23', NULL, '1301', 'fração ideal de terreno de 0,01533', '2 (duas) vagas de garagem, de número 17 e 17A, todas localizadas no Térreo'),
  ('H23', NULL, '1302', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 11 e 12, todas localizadas no Semienterrado'),
  ('H23', NULL, '1303', 'fração ideal de terreno de 0,02165', '2 (duas) vagas de garagem, de número 9 e 10, todas localizadas no Semienterrado'),
  ('H23', NULL, '1304', 'fração ideal de terreno de 0,01483', '1 (uma) vaga de garagem estendida com 10,0x2,5m, de número 5, localizada no Subsolo'),
  ('H23', NULL, '1401', 'fração ideal de terreno de 0,02623', '2 (duas) vagas de garagem, de número 14 e 15, todas localizadas no Térreo'),
  ('H23', NULL, '1402', 'fração ideal de terreno de 0,02241', '2 (duas) vagas de garagem, de número 18 e 19, todas localizadas no Térreo'),
  ('H23', NULL, '1403', 'fração ideal de terreno de 0,02163', '2 (duas) vagas de garagem, de número 16 localizada no Térreo e 13 localizada no Semienterrado'),
  ('H23', NULL, '1404', 'fração ideal de terreno de 0,02556', '2 (duas) vagas de garagem, de número 12 e 13, todas localizadas no Térreo'),
  ('H23', NULL, '1501', 'fração ideal de terreno de 0,0249', '3 (três) vagas de garagem, de número 9, 10 e 11, todas localizadas no Térreo'),
  ('H23', NULL, '1502', 'fração ideal de terreno de 0,02304', '3 (três) vagas de garagem, de número 6, 7 e 8, todas localizadas no Térreo'),
  ('SMK', NULL, '101', 'fração ideal de terreno de 0,006513', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '102', 'fração ideal de terreno de 0,006385', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '103', 'fração ideal de terreno de 0,006568', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '104', 'fração ideal de terreno de 0,005857', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '105', 'fração ideal de terreno de 0,005451', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '106', 'fração ideal de terreno de 0,006732', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '107', 'fração ideal de terreno de 0,009996', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '108', 'fração ideal de terreno de 0,009996', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '109', 'fração ideal de terreno de 0,009996', '1 (uma) vaga de garagem localizada no Térreo'),
  ('SMK', NULL, '301', 'fração ideal de terreno de 0,0131079', '2 (duas) vagas de garagem, de número 89 e 90, todas localizadas no Pavimento Intermediário'),
  ('SMK', NULL, '302', 'fração ideal de terreno de 0,0141793', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 75, localizada no Subsolo 1'),
  ('SMK', NULL, '401', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 6 e 7, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '501', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 5 e 17, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '601', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 50 e 51, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '701', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 48 e 49, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '801', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 96 e 97, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '901', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 110 e 111, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1001', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 106 e 107, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1101', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 15 e 16, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1201', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 13 e 14, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1301', 'fração ideal de terreno de 0,013136', '2 (duas) vagas de garagem, de número 46 e 47, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '402', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 108 e 109, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '502', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 3 e 4, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '602', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 1 e 2, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '702', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 104 e 105, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '802', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 8 e 9, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '902', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 52 e 53, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1002', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 134 e 135, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1102', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 112 e 113, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1202', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 10 e 11, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1302', 'fração ideal de terreno de 0,0128093', '2 (duas) vagas de garagem, de número 93 e 94, todas localizadas no Pavimento Intermediário'),
  ('SMK', NULL, '403', 'fração ideal de terreno de 0,008851', '1 (uma) vaga de garagem, de número 12, localizada no Subsolo 2'),
  ('SMK', NULL, '503', 'fração ideal de terreno de 0,008851', '1 (uma) vaga de garagem, de número 45, localizada no Subsolo 1'),
  ('SMK', NULL, '603', 'fração ideal de terreno de 0,008851', '1 (uma) vaga de garagem, de número 100, localizada no Garagem Elevada'),
  ('SMK', NULL, '703', 'fração ideal de terreno de 0,008851', '1 (uma) vaga de garagem, de número 103, localizada no Garagem Elevada'),
  ('SMK', NULL, '803', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,2m, de número 19, localizada no Subsolo 2'),
  ('SMK', NULL, '903', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,2m, de número 57, localizada no Subsolo 1'),
  ('SMK', NULL, '1003', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,2m, de número 115, localizada no Garagem Elevada'),
  ('SMK', NULL, '1103', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 18, localizada no Subsolo 2'),
  ('SMK', NULL, '1203', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 39, localizada no Subsolo 2'),
  ('SMK', NULL, '1303', 'fração ideal de terreno de 0,0091915', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 117, localizada no Garagem Elevada'),
  ('SMK', NULL, '404', 'fração ideal de terreno de 0,0089089', '1 (uma) vaga de garagem, de número 125, localizada no Garagem Elevada'),
  ('SMK', NULL, '504', 'fração ideal de terreno de 0,0089089', '1 (uma) vaga de garagem, de número 91, localizada no Pavimento Intermediário'),
  ('SMK', NULL, '604', 'fração ideal de terreno de 0,0089089', '1 (uma) vaga de garagem, de número 95, localizada no Pavimento Intermediário'),
  ('SMK', NULL, '704', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 24, localizada no Subsolo 2'),
  ('SMK', NULL, '804', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 25, localizada no Subsolo 2'),
  ('SMK', NULL, '904', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 26, localizada no Subsolo 2'),
  ('SMK', NULL, '1004', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 60, localizada no Subsolo 1'),
  ('SMK', NULL, '1104', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 63, localizada no Subsolo 1'),
  ('SMK', NULL, '1204', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 61, localizada no Subsolo 1'),
  ('SMK', NULL, '1304', 'fração ideal de terreno de 0,0092494', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 62, localizada no Subsolo 1'),
  ('SMK', NULL, '405', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 23, localizada no Subsolo 2'),
  ('SMK', NULL, '505', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 20, localizada no Subsolo 2'),
  ('SMK', NULL, '605', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 119, localizada no Garagem Elevada'),
  ('SMK', NULL, '705', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 116, localizada no Garagem Elevada'),
  ('SMK', NULL, '805', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 92, localizada no Pavimento Intermediário'),
  ('SMK', NULL, '905', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 131, localizada no Garagem Elevada'),
  ('SMK', NULL, '1005', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 130, localizada no Garagem Elevada'),
  ('SMK', NULL, '1105', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 28, localizada no Subsolo 2'),
  ('SMK', NULL, '1205', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 126, localizada no Garagem Elevada'),
  ('SMK', NULL, '1305', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 127, localizada no Garagem Elevada'),
  ('SMK', NULL, '406', 'fração ideal de terreno de 0,0127334', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 27, localizada no Subsolo 2'),
  ('SMK', NULL, '506', 'fração ideal de terreno de 0,0127334', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 120, localizada no Garagem Elevada'),
  ('SMK', NULL, '606', 'fração ideal de terreno de 0,0127334', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 136, localizada no Garagem Elevada'),
  ('SMK', NULL, '706', 'fração ideal de terreno de 0,0127334', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 121, localizada no Garagem Elevada'),
  ('SMK', NULL, '806', 'fração ideal de terreno de 0,0127334', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 122, localizada no Garagem Elevada'),
  ('SMK', NULL, '906', 'fração ideal de terreno de 0,0128185', '2 (duas) vagas de garagem, de número 29 e 30, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1006', 'fração ideal de terreno de 0,0128185', '2 (duas) vagas de garagem, de número 33 e 34, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1106', 'fração ideal de terreno de 0,0128185', '2 (duas) vagas de garagem, de número 21 e 22, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1206', 'fração ideal de terreno de 0,0128185', '2 (duas) vagas de garagem, de número 66 e 67, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1306', 'fração ideal de terreno de 0,0128185', '2 (duas) vagas de garagem, de número 128 e 129, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '407', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 54 e 55, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '507', 'fração ideal de terreno de 0,0119589', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 124, localizada no Garagem Elevada'),
  ('SMK', NULL, '607', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 68 e 69, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '707', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 87 e 88, todas localizadas no Pavimento Intermediário'),
  ('SMK', NULL, '807', 'fração ideal de terreno de 0,0119589', '1 (uma) vaga de garagem estendida com 9,0x2,5m, de número 123, localizada no Garagem Elevada'),
  ('SMK', NULL, '907', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 31 e 32, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1007', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 35 e 36, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1107', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 37 e 38, todas localizadas no Subsolo 2'),
  ('SMK', NULL, '1207', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 64 e 65, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1307', 'fração ideal de terreno de 0,0120441', '2 (duas) vagas de garagem, de número 70 e 71, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1401', 'fração ideal de terreno de 0,021198', '3 (três) vagas de garagem, de número 43, 44 e 56, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1402', 'fração ideal de terreno de 0,0128091', '2 (duas) vagas de garagem, de número 98 e 99, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1403', 'fração ideal de terreno de 0,016955', '2 (duas) vagas de garagem, de número 101 e 102, todas localizadas no Garagem Elevada'),
  ('SMK', NULL, '1404', 'fração ideal de terreno de 0,0145246', '2 (duas) vagas de garagem, de número 85 e 86, todas localizadas no Pavimento Intermediário'),
  ('SMK', NULL, '1405', 'fração ideal de terreno de 0,0064127', '1 (uma) vaga de garagem, de número 114, localizada no Garagem Elevada'),
  ('SMK', NULL, '1406', 'fração ideal de terreno de 0,0130058', '2 (duas) vagas de garagem, de número 58 e 59, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1407', 'fração ideal de terreno de 0,0214', '3 (três) vagas de garagem, de número 72, 73 e 74, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1501', 'fração ideal de terreno de 0,022043', '3 (três) vagas de garagem, de número 40, 41 e 42, todas localizadas no Subsolo 1'),
  ('SMK', NULL, '1502', 'fração ideal de terreno de 0,023235', '3 (três) vagas de garagem, de número 118, 132 e 133, todas localizadas no Garagem Elevada');